name: Dependency-Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '23'  # Ajusta según tu proyecto
    
    - name: Download and extract OWASP Dependency-Check
      run: |
        curl -L -o dependency-check.zip https://github.com/jeremylong/DependencyCheck/releases/download/v9.0.10/dependency-check-9.0.10-release.zip
        unzip dependency-check.zip
        extracted_dir=$(find . -maxdepth 1 -type d -name "dependency-check-*" | head -n 1)
        echo "Extracted dir: $extracted_dir"
        chmod +x "$extracted_dir/bin/dependency-check.sh"
        mv "$extracted_dir" ./dependency-check


    - name: Run Dependency-Check
      run: |
        ./dependency-check/bin/dependency-check.sh \
          --project "apiusuarioscriticas" \
          --scan . \
          --format "HTML" \
          --out reports

    - name: Upload report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check-report
        path: reports/dependency-check-report.html